<?php
return [
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/last.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Working Motivation",
        "description"=> "Never give up on what you really want to do. The person with big dreams is more powerful than the one with all the facts.",
        "views"=> 37,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/knowledge.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "knowledge",
        "description"=> "Create a personal vision statement.",
        "views"=> 32,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/kedar-3.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Baaromass Travels",
        "description"=> "June to August is monsoon and should best be avoided as the area is prone to landslides.",
        "views"=> 42,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/kedar-1.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Baaromass Travels",
        "description"=> "The Himalayas is full of stories and myth. We love stories and so we look for them wherever we go.",
        "views"=> 117,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladakh-4.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "You can get great panoramic views from all over the city. There aren’t really any restrictions on where you can go here so explore away!",
        "views"=> 15,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladkah3.5.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "You can’t really get bored, even just if you gaze at the scenery around you.",
        "views"=> 13,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladakh.3.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "The next day, we had a chai together, thanked the guys at KC garden, and then went to try and find a room.",
        "views"=> 14,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladkah2.5.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "It was really generous of him as he didn’t have to offer anything at all. He also didn’t charge which was really kind.",
        "views"=> 14,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladkah-2.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "You’ll pass through valleys, mountain passes, and waterfalls. There’s absolutely no sign of life around in many parts and it’s an experience you won’t forget.",
        "views"=> 14,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladakh1.5.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "The best time to visit is actually in the monsoon season between June – September as Ladakh is a dry spot in a country of constant rain!",
        "views"=> 14,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/ladkah1.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/thumbnail/thumnail.jpg",
        "location"=> "Weekend Trips",
        "description"=> "Julley from Leh! That means Hello in Ladakh and you’ll find that everyone here is itching to say it to you.\r\n\r\nLeh is the super friendly mountain city that is waiting for you to visit them.",
        "views"=> 14,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/dehradun-status-video-dehradun-city-status-dehradun-whatsapp-status-1440-ytshorts.savetube.me.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/dehradun-status-video-dehradun-city-status-dehradun-whatsapp-status-1440-ytshorts.savetube.me.mp4",
        "location"=> "Inside the city,",
        "description"=> "This is a unique city, this Dehradun.  It was love that dragged me here the first time.  That first time, I remember Dehradun being a unique kind of quaint.",
        "views"=> 12,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/men+vs+boys+lifestyle+%E2%98%BA%EF%B8%8F%F0%9F%98%8E%F0%9F%94%A5%5B+Dark+light+%5D%23shorts.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/men+vs+boys+lifestyle+%E2%98%BA%EF%B8%8F%F0%9F%98%8E%F0%9F%94%A5%5B+Dark+light+%5D%23shorts.mp4",
        "location"=> "Being Motivated",
        "description"=> "You can get everything in life you want if you will just help enough other people get what they want.”",
        "views"=> 10,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/gal-gadot-on-getting-casted-as-wonder-woman-ytshorts.savetube.me+(1).mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/gal-gadot-on-getting-casted-as-wonder-woman-ytshorts.savetube.me+(1).mp4",
        "location"=> "Wonder woman",
        "description"=> "Wonder Woman is a compassionate caring, stubborn, opinionated, highly competitive, outgoing, immortal Amazon. Wonder Woman is a warrior born. She tries to avoid conflict but if pressed she will engage in battle and on occasion lose herself in the pleasure of battle.",
        "views"=> 7,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/Is+not+the+Solution+%E2%98%9D%EF%B8%8F%F0%9F%99%84motivational+quotes+_+motivational+status+video.%23shorts+%23viral+%23motivational.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/Is+not+the+Solution+%E2%98%9D%EF%B8%8F%F0%9F%99%84motivational+quotes+_+motivational+status+video.%23shorts+%23viral+%23motivational.mp4",
        "location"=> "being Focused",
        "description"=> "Work like there is someone working 24 hours a day to take it away from you.",
        "views"=> 8,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0012.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/DSC036892B2528Custom2529.jpg",
        "location"=> "Banjarawala",
        "description"=> "Two are better than one.",
        "views"=> 28,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0011.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/dvs.jfif",
        "location"=> "Kanwali Road",
        "description"=> "Keep your face always toward the sunshine, and shadows will fall behind you.",
        "views"=> 83,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0010.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/sdac.jpg",
        "location"=> "Premnagar",
        "description"=> "It’s always better when we’re together.",
        "views"=> 33,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0009.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/DSC036892B2528Custom2529.jpg",
        "location"=> "Shimla Road",
        "description"=> "Life has got all those twists and turns. You’ve got to hold on tight and off you go.",
        "views"=> 75,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=> 1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0008.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/bb.jfif",
        "location"=> "Dehrakhas",
        "description"=> "You’re the closest to heaven, that I’ll ever be",
        "views"=> 93,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0007.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/a.jpg",
        "location"=> "Kuanwala",
        "description"=> "The bad news is time flies. The good news is you’re the pilot.",
        "views"=> 17,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [   "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0006.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/sdac.jpg",
        "location"=> "Dalanwala",
        "description"=> "I am who I am because of you. You are every reason, every hope, and every dream I’ve ever had.",
        "views"=> 52,
        "comments"=> 0,
        "reported"=> 0,
    ],

    [   "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0005.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/fafs.jfif",
        "location"=> "Patel Nagar",
        "description"=> "There is nothing impossible to they who will try.",
        "views"=> 25,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0004.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/dvs.jfif",
        "location"=> "Canal Road",
        "description"=> "Love is that condition in which the happiness of another person is essential to your own.",
        "views"=> 14,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0003.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/DSC036892B2528Custom2529.jpg",
        "location"=> "Sahastradhara",
        "description"=> "Nothing is impossible. The word itself says ‘I’m possible!",
        "views"=> 59,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0002.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/d.png",
        "location"=> "G.M.S Road",
        "description"=> "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.",
        "views"=> 103,
        "comments"=> 0,
        "reported"=> 0,
    ],
    [
        "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0001.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/bb.jfif",
        "location"=> "Mussoorie Rd",
        "description"=> "When you have a dream, you’ve got to grab it and never let go.",
        "views"=> 36,
        "comments"=> 1,
        "reported"=> 0,
    ],
    [
        "user_id"=>1,
        "city_id"=> 80,
        "videoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/VID-20220526-WA0000.mp4",
        "photoUrl"=> "https://tooday.s3.ap-south-1.amazonaws.com/a.jpg",
        "location"=> "Rajpur Road",
        "description"=> "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
        "views"=> 76,
        "comments"=> 0,
        "reported"=> 0,
    ]
];

